import reactor_ui.reactor_upscale_ui as ui_upscale
import reactor_ui.reactor_tools_ui as ui_tools
import reactor_ui.reactor_settings_ui as ui_settings
import reactor_ui.reactor_main_ui as ui_main
import reactor_ui.reactor_detection_ui as ui_detection
